### PR TITLE
Fix flaky tests in AsyncTest

### LINKED ISSUE #1070: Investigate flaky test in AsyncTest
In a few builds today, this error happened:

```
AsyncTest$WaitFor.shouldSucceed_WhenTheFutureCompletes_BeforeTimeout:273 »
   Async TimeoutException occurred (maximum wait was specified as 250 MILLISECONDS)
```

Why is this happening when the `ConcurrentTask` used inside  this test has a default "task" duration of _10_ milliseconds?

### PR DESCRIPTION
**Pull request by sleberknight**
Ensure that the tests all pass consistently by canceling the futures in the tests
where we expect to timeout before the tasks complete. Without canceling them,
tests which call methods in Async that use the common ForkJoinPool can be
blocked by tasks that are still executing from previous tests! So, in the three tests
where waitFor/waitForAll/waitForAllIgnoringTypes time out before the tasks complete,
wrap the assertions in a try/finally and cancel the futures in the finally block. This
commit also removes the RetryingTest annotations on the four tests which had them
and replaces them with the standard JUnit Test annotation. Hopefully this will be
the last time we ever need to deal with flaky tests in Async.

Closes #1070

### CODE REVIEW

**Comment by sleberknight** [comment]
This relates to #1070 

Pretty sure it has nothing to do with ForkJoinPool init time and that it is due to tasks from previous tests that used the common pool and which are still executing and _blocking_ the new tests...which then causes them to exceed the timeout and fail

**Comment by sleberknight** [comment]
I don't really understand why this only happens when running in GitHub actions - I'm using the same JDK on my laptop and when using Gitpod, so only thing I can think of is differences in the JVM behavior on different operating systems, e.g. on my MacBook Pro versus in Gitpod versus in GitHub Actions.

File: src/test/java/org/kiwiproject/concurrent/AsyncTest.java [hunk 1]
```diff
@@ -445,7 +455,12 @@ void shouldTimeout_WhenTaskTakesLongerThan_MaxTimeout() {
         }
     }
 
-    private void confirmCompletion(ConcurrentTask task) {
+    private static <T> void cancel(CompletableFuture<T> future) {
```
Comment (sleberknight) [inline src/test/java/org/kiwiproject/concurrent/AsyncTest.java:458]: Document why this is necessary
