### PR TITLE
Switch from re-retrying to retrying-again (breaking API changes)

### LINKED ISSUE #481: Investigate changes needed to switch to re-retrying fork of guava-retrying
Investigate what changes will be needed in order to switch from guava-retrying to the fork￼ed re-retrying library. That fork made some fundamental changes, most specifically it removed the generic type parameter from the Retryer class; instead the type parameter is only on the call method￼. 

It also changed so that it no longer throws￼ ExecutionException, and I know that our code has special handling for that. 

We will then be in a better position to determine whether we want to fork the fork, since it is no longer being maintained either￼.

Link to fork: https://github.com/rhuffman/re-retrying

### LINKED ISSUE #531: Switch from re-retrying to kiwiproject's retrying-again
Now that [retrying-again](https://github.com/kiwiproject/retrying-again) has been officially released (first release is [0.5.0](https://github.com/kiwiproject/retrying-again/releases/tag/v0.5.0)), we can switch kiwi to use it.

Since there were some breaking API changes in retrying-again such as throwing `Exception` instead of `Throwable`, this switch **will include breaking API changes**. As is our policy, we are not yet at 1.0.0 so we reserve the right to change APIs.

### PR DESCRIPTION
**Pull request by sleberknight**
NOTE: The package for retrying-again is the same as the one in kiwi
which (for now) lets us access package-private members. If (when?) we
update to make proper use of the JPMS (module system) this will most
likely break and we'd need to change that somehow.

* Change POM to use org.kiwiproject:retrying-again:0.5.0 and remove
  the (now unnecessary) guava exclusion

* Update KiwiRetryer to use retrying-again
  - API breaking change: exceptionPredicates are Exception not Throwable
  - call now catches InterruptedException
  - call no longer catches ExecutionException
  - the internal Retryer is no longer generic
  - remove (now redundant) warning suppression for Unstable API usage
  - fix generic in LoggingRetryListener (is now wildcard)
  - fix code in logExceptionAttempt to call attempt.getException()

* Update KiwiRetryerException
  - Constructor now accepts Exception not Throwable, and it validates
    the type is RetryException or InterruptedException
  - Update unwrapKiwiRetryerException to remove handling for
    ExecutionException which is no longer thrown by Retryer
  - Add some new methods:
    isCauseRetryException, isCauseInterruptedException, getLastAttempt,
    getNumberOfFailedAttempts, and unwrapAsRetryException

* Update KiwiRetryerPredicates
  - all the Predicates are now java.util.Predicate
  - the exception Predicates now use Exception, not Throwable

Closes #531
Closes #481

### CODE REVIEW

File: src/main/java/org/kiwiproject/retry/KiwiRetryerException.java [hunk 1]
```diff
@@ -1,68 +1,65 @@
...
-     * a null cause, this method returns an {@link Optional} to indicate there might not actually be an exception
-     * cause.
+     * Since it is possible for an {@link Attempt} to fail without an exception, this method returns an {@link Optional}
+     * to indicate there might not actually be an exception cause.
      *
      * @param kiwiRetryerEx the exception to unwrap
      * @return the unwrapped cause
      * @see #unwrapKiwiRetryerExceptionFully(KiwiRetryerException)
      */
     public static Optional<Throwable> unwrapKiwiRetryerException(KiwiRetryerException kiwiRetryerEx) {
```
Comment (chrisrohr) [inline src/main/java/org/kiwiproject/retry/KiwiRetryerException.java:40]: Does this need to be `Throwable`?  I'm assuming yes based on the `getCause` returning a `Throwable`, but wanted to check since you just went through all that effort to stop using `Throwable`s.

**Review by chrisrohr — APPROVED** [review]

File: src/main/java/org/kiwiproject/retry/KiwiRetryerException.java (hunk 1 above)
Comment (sleberknight) [reply src/main/java/org/kiwiproject/retry/KiwiRetryerException.java:40]: Yes, that's correct.`Exception#getCause` returns `Throwable` since is defined in `Throwable`. So, we have little choice (assuming we don't want to cast and run the risk of a `ClassCastException`), even though it always _should_ be only `Exception`
